Add session storage support with function option
ryangjchandler/fern pull request #1
Opened 2021-07-23 10:22 UTC by ekwoka

Great work dude. I've never done a pull request before, so please let me know if I did anything wrong in this process, just edited the file on github. Worked on a separate thing I was playing with. Seems this could be the cleanest way to add session storage support without breaking anything for anyone else and keeping it DRY.

2021-07-23 10:26 UTC, ekwoka commented
forgot to write how to use:

Alpine.persistedStore('this is in', 'localStorage');
Alpine.persistedStore('this is in', 'sessionStorage', 0);

2021-07-23 10:41 UTC, ryangjchandler commented on src/index.js
> +        let storage = type ? localStorage : sessionStorage
I don't think using a numeric flag / `bool` here really makes sense. Why not just allow the user to pass the storage object through instead?

2021-07-23 10:42 UTC, ryangjchandler requested changes

2021-07-23 10:42 UTC, ryangjchandler commented on src/index.js
> +    Alpine.persistedStore = function (name, value, type = 1) {
```suggestion
    Alpine.persistedStore = function (name, value, storage = window.localStorage) {
```

2021-07-23 10:42 UTC, ryangjchandler commented on src/index.js
> +        let storage = type ? localStorage : sessionStorage
```suggestion
```

2021-07-23 11:05 UTC, ekwoka commented on src/index.js
> +    Alpine.persistedStore = function (name, value, type = 1) {
Ooh smart!

2021-07-23 11:11 UTC, ryangjchandler commented
@ekwoka Can you confirm that these changes work?

2021-07-23 13:04 UTC, ekwoka commented
> @ekwoka Can you confirm that these changes work?

@ryangjchandler This works brilliantly

2021-07-23 13:07 UTC, ryangjchandler commented
@ekwoka Could you also update the documentation?

2021-07-23 13:38 UTC, ryangjchandler requested changes

2021-07-23 13:38 UTC, ryangjchandler commented on README.md
> +To use `sessionStorage`, or another custom storage that uses the same syntax, in place of `localStorage`, simply pass an optional third argument containing the storage object when creating the store.
```suggestion
To use `sessionStorage`, or another custom storage that has an identical API, simply pass an optional third argument containing the storage object when creating the store.
```

2021-07-23 13:38 UTC, ekwoka commented
@ryangjchandler done. Should I do the build as well? Is that normal?

2021-07-23 13:47 UTC, ryangjchandler commented
Yes please, if you could build and push those files.

2021-07-28 03:08 UTC, ekwoka commented
@ryangjchandler 

Done. I guess you didn't see that I built it a while ago haha

2022-08-18 07:55 UTC, closed without merging